### ISSUE TITLE
Unable to serialize EntityDescriptor containing a Signature node

### ISSUE THREAD

**Issue by zluiten** [lightSAML/lightSAML#110]
```
$xml = ''; // valid xml here containing a Signature element

$entityDescriptor = EntityDescriptor::loadXml($xml);

// do some validation

$serializationContext = new SerializationContext();
$document = $serializationContext->getDocument();
$entityDescriptor->serialize($document, $serializationContext);
// \LogicException is thrown with message 'SignatureXmlReader can not be serialized'

$serializedXml = $document->saveXML();
```

I would expect the Signature dom element representation to be serialisable. Any thoughts on this?

**Comment by tmilos** [comment]
In order to serialize object model to XML with a signature you would need to have an instance of `SignatureWriter` as signature in order to be able to sign the XML with your private key. Instances of `SignatureReader` only have public key and are not able to sign the document, but only to verify already made signature. 

You can not take a signed XML document of ie some IDP, deserialize it into the object model, modify it, and serialize it back to the XML all with the original signature - that would make old signature invalid on the new document. On the other hand, if you don't want to modify it, then there's no need to deserialize it

**Comment by zluiten** [comment]
Makes sense @tmilos. Thanks for the explanation!
