### ISSUE TITLE
Parsing large XML metadata files

### ISSUE THREAD

**Issue by nogrp** [lightSAML/lightSAML#22]
First off - thank you for the wonderful library, I removed "simple"samlphp instantly after having discovered this, I simply love it. Awesome job!

Onto the question - how to parse large xml files containing metadata? Specifically, I tried extracting information from this: http://metadata.ukfederation.org.uk/ukfederation-metadata.xml

The code I used:

``` php
// Path in the FS so I don't have to fetch from URL 
$xml = storage_path('xml/federation.xml'); 

$ed = \LightSaml\Model\Metadata\EntityDescriptor::load($xml);
```

First error:
`Argument 1 passed to LightSaml\Model\Metadata\EntityDescriptor::deserialize() must be an instance of DOMElement, instance of DOMComment given`

I can see that this has been mentioned in #18 

After having removed all comments to check whether lightSAML will parse this federation metadata file, I got this:

`DOMDocument::loadXML(): AttValue: ' expected in Entity, line: 285539`

At this point I decided to ask here:
- How to parse the federation metadata? Should I use `XMLReader` to parse the file line by line and then feed the results to lightSAML?
- Is there any plan to add large xml file parser / metadata parser?
- Have I missed anything obvious? :)

**Comment by tmilos** [comment]
@nogrp Glad you like it and find it more simple ;)
Issue with leading comments is known from #18, and think it's fixed in PR #23 ... have just to wait for CI and merge it.

Regarding your issue with large file... It works for me, but with one small change... Document on http://metadata.ukfederation.org.uk/ukfederation-metadata.xml is `EntitiesDescriptor` not a single `EntityDescriptor`.

So, until #23 is merged and released (soon), you can do it like this

``` php
$path = storage_path('xml/federation.xml'); 

$eds = new \LightSaml\Model\Metadata\EntitiesDescriptor();
$deserializationContext = new DeserializationContext();
$deserializationContext->getDocument()->load($path);
$root = $deserializationContext->getDocument()->firstChild;
while ($root instanceof \DOMComment) {
    $root = $root->nextSibling;
}
$eds->deserialize($root, $deserializationContext);
// or just an ugly hard code
$eds->deserialize($deserializationContext->getDocument()->firstChild->nextSibling, $deserializationContext);

// and now pick some EntityDescriptor from it
// $eds->getAllEntityDescriptors() or $eds->getByEntityId('some-id');
```

Once #23 is merged, you will be able to do

``` php
$path = storage_path('xml/federation.xml'); 
$eds = \LightSaml\Model\Metadata\EntitiesDescriptor::load($path);
```

Though... it takes a while until it's parsed, second or two... For 21Mb it's expected to lag a bit... But that's a topic for some optimization maybe... will see. Anyway, if you don't need all EntityDescriptors from that document, I recommend extracting only those few you will be using to improve performance.

Anyway, please keep this issue, open, I out of time atm, but would like to try what you did, to load `EntitiesDescriptor` document with `EntityDescriptor` class and adjust the error message to be more user friendly and descriptive.

**Comment by tmilos** [comment]
@nogrp the PR #23 is merged, so leading xml comments are not a problem anymore, and also in PR #24 new `Metadata` class was added which can be used for easy loading of metadata xml documents, it will return either `EntityDescriptor` or `EntitiesDescriptor`. Parsing large xml document you specified is tested [here](https://github.com/lightSAML/lightSAML/blob/master/tests/LightSaml/Tests/Functional/Model/Metadata/EntitiesDescriptorFunctionalTest.php#L212) and no changes were required.

**Comment by tmilos** [comment]
Closing the issue, if you think it's not resolved, please re-open or create a new one.

**Comment by nogrp** [comment]
@tmilos  - I just pulled and tried it out, the `Metadata` class solves the issues I had, thank you for this super-quick response! If I have any other issues, I'll make sure to report back. Once more, thanks for the great library :)
