### ISSUE TITLE
Validate inbound response against XML schema

### ISSUE THREAD

**Issue by bartvw** [lightSAML/lightSAML#30]
According to [OWASP's SAML Security Cheat Sheet](https://www.owasp.org/index.php/SAML_Security_Cheat_Sheet), schema validation should always be performed on XML documents prior to using them for security-related purposes. 
We've currently solved this with a listener on `Events::BINDING_MESSAGE_RECEIVED`, but I think it actually belongs in the library itself.

**Comment by tmilos** [comment]
I see the point. But still that is just a recommendation. LightSAML had just recently fixed the order of elements in XML to be XSD valid #21 and before that SP was working w/out errors both with ADFS and Shibboleth. True, I haven't tried sending them the `Response`, maybe they XSD validate the `Response` and not `AuthnRequest`, and the fix was mostly about the Response and Metadata.

Anyway, @bartvw  do you think that Response XSD validation should be hard-coded and always performed, or maybe somehow configurable and optional?

**Comment by bartvw** [comment]
I think optional would be better than hard-coded, so it's possible to skip it when dealing with a party that isn't 100% compliant.

**Comment by bartvw** [comment]
@tmilos It seems this was fixed in #56, correct?

**Comment by tmilos** [comment]
No, just a validator class was made, but not an action that will actually call it and do the validation in the profile action... that action is still pending
